locale:
  - ar-SA
  - ca-ES
  - cs-CZ
  - da-DK
  - de-DE
  - el-GR
  - es-ES
  - et-EE
  - fi-FI
  - fr-FR
  - he-IL
  - hy-AM
  - hu-HU
  - id-ID
  - it-IT
  - ja-JP
  - ko-KR
  - lt-LT
  - nl-NL
  - no-NO
  - pl-PL
  - pt-BR
  - ro-RO
  - ru-RU
  - tr-TR
  - uk-UA
  - vi-VN
  - zh-CN
  - zh-TW
