{% set name = "jupyterlab-language-pack" %}
{% set version = "4.4.post2" %}

package:
  name: {{ name|lower }}-{{ locale|lower }}
  version: {{ version }}

source:
  - folder: ar-SA
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ar-SA/{{ name | replace('-', '_') }}_ar_sa-{{ version }}.tar.gz
    sha256: 1ff6ae3d8d913d65fcd4909c5d2be27368d64983f8aa86e91d30bd3a98bcd6cf
  - folder: ca-ES
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ca-ES/{{ name | replace('-', '_') }}_ca_es-{{ version }}.tar.gz
    sha256: ea3c8cf288b337d2879bcbcc908fd355dbe12375302df479d52033c03686845d
  - folder: cs-CZ
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-cs-CZ/{{ name | replace('-', '_') }}_cs_cz-{{ version }}.tar.gz
    sha256: 34b47b4dc08ecb358ff54e57ffb53cd2c204fc0d0d3a474396467aece411f0f9
  - folder: da-DK
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-da-DK/{{ name | replace('-', '_') }}_da_dk-{{ version }}.tar.gz
    sha256: 3d7be6850d704aa39c35988eed8b4b5e69fc0e6c07e55b2406d3561b29e5bd6a
  - folder: de-DE
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-de-DE/{{ name | replace('-', '_') }}_de_de-{{ version }}.tar.gz
    sha256: 8b802287a0b2b9ede3f583884dcce1ba85b492dd03942d911d9e12c54a3dffc0
  - folder: el-GR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-el-GR/{{ name | replace('-', '_') }}_el_gr-{{ version }}.tar.gz
    sha256: ac125caf3603d3b199e2577fb7d54663114b15b498944475cee695396807d324
  - folder: es-ES
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-es-ES/{{ name | replace('-', '_') }}_es_es-{{ version }}.tar.gz
    sha256: 1b92b59ef6f25307c0205a03d52d950e939bbd2437ebf5e631580b8fb7cb9849
  - folder: et-EE
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-et-EE/{{ name | replace('-', '_') }}_et_ee-{{ version }}.tar.gz
    sha256: 89465e22548d14eb7db7339fbea9974af4e92fd123943333d89da61fba33039e
  - folder: fi-FI
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-fi-FI/{{ name | replace('-', '_') }}_fi_fi-{{ version }}.tar.gz
    sha256: eb3cd33a44ca6143b98d5d930f14715ec46f4154098e7be77f8c916a08df632a
  - folder: fr-FR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-fr-FR/{{ name | replace('-', '_') }}_fr_fr-{{ version }}.tar.gz
    sha256: 657144af6d17ec2d256fe435e9a2727659fad2c3cf64ef40c05755eaf9a427f8
  - folder: he-IL
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-he-IL/{{ name | replace('-', '_') }}_he_il-{{ version }}.tar.gz
    sha256: 0e2bfbef78258b61c9eb5d4f4cd89b4ef69f6bd213a914b101ba619076a1b3f5
  - folder: hy-AM
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-hy-AM/{{ name | replace('-', '_') }}_hy_am-{{ version }}.tar.gz
    sha256: 83b8734ed6ea3c89ade2c8aa0ba76048d186ea7ebe59089ddfac65a0782cde7d
  - folder: hu-HU
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-hu-HU/{{ name | replace('-', '_') }}_hu_hu-{{ version }}.tar.gz
    sha256: 19173f5ca08eeea831ffd8c33430872478f8249464e5c4e91451692e29f4b955
  - folder: id-ID
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-id-ID/{{ name | replace('-', '_') }}_id_id-{{ version }}.tar.gz
    sha256: 62b444842d516c659c830143ce224a29765fc9a65274ad2c04007b07d1ee4279
  - folder: it-IT
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-it-IT/{{ name | replace('-', '_') }}_it_it-{{ version }}.tar.gz
    sha256: 26d36f0036bdc626e77977fa93104c7c42bff42ed9a122bfd7339b2308ea004d
  - folder: ja-JP
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ja-JP/{{ name | replace('-', '_') }}_ja_jp-{{ version }}.tar.gz
    sha256: 9594c7e464ba8047f1e081fb4ac49981bc965dd31dc1f0360616c7de2d2c4830
  - folder: ko-KR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ko-KR/{{ name | replace('-', '_') }}_ko_kr-{{ version }}.tar.gz
    sha256: 3ba44531d506a32146937f3f81a8806e0255590ec77daac77218fc715b1e4dbb
  - folder: lt-LT
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-lt-LT/{{ name | replace('-', '_') }}_lt_lt-{{ version }}.tar.gz
    sha256: d6cc877ef457e746ad1fa0945e78d6f962aae52e141ab3538bbad4010b9cfd64
  - folder: nl-NL
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-nl-NL/{{ name | replace('-', '_') }}_nl_nl-{{ version }}.tar.gz
    sha256: 0a36b9637a614fa9f93c77a3f15cac47d35bcbd8ad70e79d56ea74aa55b2a0ab
  - folder: no-NO
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-no-NO/{{ name | replace('-', '_') }}_no_no-{{ version }}.tar.gz
    sha256: 7d8c6268afd0a6a994c5d2eaebcb83d8a09eddf46ea73022703203e778916291
  - folder: pl-PL
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-pl-PL/{{ name | replace('-', '_') }}_pl_pl-{{ version }}.tar.gz
    sha256: cbb12f0a5e7b24b793aeaad9181eab1cbcbff9484a56398ea94fd76e1d644cd7
  - folder: pt-BR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-pt-BR/{{ name | replace('-', '_') }}_pt_br-{{ version }}.tar.gz
    sha256: 0315a6f056dc47a6d4143088014de1372ae7116c375c6c0989dfa45d1b2d5df9
  - folder: ro-RO
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ro-RO/{{ name | replace('-', '_') }}_ro_ro-{{ version }}.tar.gz
    sha256: c0d263d13c2083fd4d5fa7d6ec22a2695cbd49b4446250c837316efea928e1eb
  - folder: ru-RU
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ru-RU/{{ name | replace('-', '_') }}_ru_ru-{{ version }}.tar.gz
    sha256: 7a2a0b3eda20f441b545c34b1d96ccde3150a9f098ac486da8ea4ecf25873954
  - folder: tr-TR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-tr-TR/{{ name | replace('-', '_') }}_tr_tr-{{ version }}.tar.gz
    sha256: 77e5a1dfbce661ea7b6c7314b7db447338a80d9fb88868ac41bf84a9beb34e0e
  - folder: uk-UA
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-uk-UA/{{ name | replace('-', '_') }}_uk_ua-{{ version }}.tar.gz
    sha256: a5d52c33be8a0bf0e40128117f61b2ccea9c701627f3a7c2c0e2c2ba6e49d53a
  - folder: vi-VN
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-vi-VN/{{ name | replace('-', '_') }}_vi_vn-{{ version }}.tar.gz
    sha256: 4608fe2144460956e9f5234a62886caffe4ebc33d165d5a533f131769ffe5d2f
  - folder: zh-CN
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-zh-CN/{{ name | replace('-', '_') }}_zh_cn-{{ version }}.tar.gz
    sha256: f9ec25800ab97186ee4cb55763e1d7facc7f0ed412dc0d46ed133caaacb28767
  - folder: zh-TW
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-zh-TW/{{ name | replace('-', '_') }}_zh_tw-{{ version }}.tar.gz
    sha256: 7e9c3aa8a5fb3d048f06f65574f3d39d2565a18e5617308ee1be6afbd70dec75

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install "./{{ locale }}" -vv --no-deps

requirements:
  host:
    - hatchling >=1.4.0
    - jupyterlab-translate >=1.2.0
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab/language-packs
  summary: JupyterLab {{ locale }} Language Pack
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ locale }}/LICENSE.txt
  doc_url: https://jupyterlab.readthedocs.io/
  dev_url: https://github.com/jupyterlab/language-packs

extra:
  feedstock-name: jupyterlab-language-packs
  recipe-maintainers:
    - blink1073
    - fcollonval
    - goanpeca
    - krassowski
