{% set name = "jupyterlab-language-pack" %}
{% set version = "3.5.post0" %}

package:
  name: {{ name|lower }}-{{ locale|lower }}
  version: {{ version }}

source:
  - folder: ar-SA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ar-SA/{{ name }}-ar-SA-{{ version }}.tar.gz
    sha256: 18a83834e629677701053fab9fc62d09415a4ffece33eecbcc8704cce3ec1408
  - folder: ca-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ca-ES/{{ name }}-ca-ES-{{ version }}.tar.gz
    sha256: 5e7fa7aa15e9c4ec603dd74680282b80d245254170f69090ad6e8db661c92568
  - folder: cs-CZ
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-cs-CZ/{{ name }}-cs-CZ-{{ version }}.tar.gz
    sha256: 1d587bb36a2743a507afd03936bab066ed0408f785c415608aaa0be13c2b30e7
  - folder: da-DK
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-da-DK/{{ name }}-da-DK-{{ version }}.tar.gz
    sha256: 18567b83f2a4a50470794d0db071155e2776d09136048cf88fd9d6ed30945981
  - folder: de-DE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-de-DE/{{ name }}-de-DE-{{ version }}.tar.gz
    sha256: 9577a2dc209987c3dcad47070c263795cb6117bf9755836a1aa5233b661d1323
  - folder: el-GR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-el-GR/{{ name }}-el-GR-{{ version }}.tar.gz
    sha256: 426ba850b36644553bf18da734931d0fe197250edcdfed74f167c1eda5023119
  - folder: es-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-es-ES/{{ name }}-es-ES-{{ version }}.tar.gz
    sha256: d2f805f5b1b784b63229ab864e6a08487c99b11b2d907ba10307c8c0ad3017f5
  - folder: et-EE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-et-EE/{{ name }}-et-EE-{{ version }}.tar.gz
    sha256: ab76df429f3d039d9b68ee9ba6a953cea5c405309fdd3db46cb444f2fff1422b
  - folder: fi-FI
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fi-FI/{{ name }}-fi-FI-{{ version }}.tar.gz
    sha256: 11c13b0bb4f8ce86aba1909d60eb61e78d094d444b048c476d1587a9f5fc3f94
  - folder: fr-FR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fr-FR/{{ name }}-fr-FR-{{ version }}.tar.gz
    sha256: 8e6d72fb442b583b8c0ca905fc2738b61f7fb7afc4ede8e10f1087bb42a171e8
  - folder: he-IL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-he-IL/{{ name }}-he-IL-{{ version }}.tar.gz
    sha256: fa525331be4662d2c13c2881481d4104f0ddf4d00a0a06820f97251da9a6ae2e
  - folder: hy-AM
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hy-AM/{{ name }}-hy-AM-{{ version }}.tar.gz
    sha256: 55104311c26ccad9cb4e1dd6bb6e3a4d8463ee31610a804271f873e17683e0cc
  - folder: hu-HU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hu-HU/{{ name }}-hu-HU-{{ version }}.tar.gz
    sha256: 22fd12c27b120a2113e5986d2aa4a95b90869a655a6c4d5d23188afe51c7686b
  - folder: id-ID
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-id-ID/{{ name }}-id-ID-{{ version }}.tar.gz
    sha256: 9e3b3c654195bdf82d9481fe8aae5d9ba53fe3c0e31303d358bda656587dd51f
  - folder: it-IT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-it-IT/{{ name }}-it-IT-{{ version }}.tar.gz
    sha256: 97a23f10a167b49decece65fb0183046f398f2ae260d9de4921edc0d6daf5fdc
  - folder: ja-JP
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ja-JP/{{ name }}-ja-JP-{{ version }}.tar.gz
    sha256: 8b0acde15ffb00a072249bcbf5fcfdc94c6354a87dcc6e82d31358d086f12a3a
  - folder: ko-KR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ko-KR/{{ name }}-ko-KR-{{ version }}.tar.gz
    sha256: 9dfb960bdb1482c7a4e027ecf347ffb8cd25bc30df232524536799a621ba4e23
  - folder: lt-LT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-lt-LT/{{ name }}-lt-LT-{{ version }}.tar.gz
    sha256: 84c0933b3889a50bca0444157e06d85e5c84c0ecde0648ef17dbc33161779d9e
  - folder: nl-NL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-nl-NL/{{ name }}-nl-NL-{{ version }}.tar.gz
    sha256: 99cfb458810a3b24df7254d30e43491fda8c5d496ed8451aa8ae6612b15a9e48
  - folder: no-NO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-no-NO/{{ name }}-no-NO-{{ version }}.tar.gz
    sha256: 252dc4a4d6ca090ca4a29db512f270224ac1eef2308d6297bb0c6c1d389e9c27
  - folder: pl-PL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pl-PL/{{ name }}-pl-PL-{{ version }}.tar.gz
    sha256: 374e011cb26f221327bb851fd1de011d792faa95a3df7a38f7701a812539466c
  - folder: pt-BR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pt-BR/{{ name }}-pt-BR-{{ version }}.tar.gz
    sha256: 1f33e5403a56d51b8e1d6de22a476676360cda8c2a2d69c63d5268c7fdfd8e2a
  - folder: ro-RO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ro-RO/{{ name }}-ro-RO-{{ version }}.tar.gz
    sha256: 640ac0906753f4492f875dfb67bb2c8e132c1eec38bb055e786fc4505031ac0e
  - folder: ru-RU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ru-RU/{{ name }}-ru-RU-{{ version }}.tar.gz
    sha256: 485fca96993ed6ba283cfeb205298389931d307997fb242e39e85bff79e5d61e
  - folder: tr-TR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-tr-TR/{{ name }}-tr-TR-{{ version }}.tar.gz
    sha256: 2d43777068c5d6a8b51c208293e4c2dfe9acc482ce132480d41190a1bd51f98f
  - folder: uk-UA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-uk-UA/{{ name }}-uk-UA-{{ version }}.tar.gz
    sha256: d7b68b48effb6103d618cbae18cd0d43509ac41e48128358834b99b16cc936e2
  - folder: vi-VN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-vi-VN/{{ name }}-vi-VN-{{ version }}.tar.gz
    sha256: b0ef33d165d6e32723f1f0431ef17b02ba2ec1fc333b5512a8c9fbd2cdecdab2
  - folder: zh-CN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-CN/{{ name }}-zh-CN-{{ version }}.tar.gz
    sha256: 3c13cd4876c5abf63b8072539b387a1332fc2a99131f2cd6aa804e78641d24a3
  - folder: zh-TW
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-TW/{{ name }}-zh-TW-{{ version }}.tar.gz
    sha256: 391aa87151f236d9f08023660783e8a44d37df185cd40fedde841d399be01d9a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install "./{{ locale }}" -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab/language-packs
  summary: JupyterLab {{ locale }} Language Pack
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ locale }}/LICENSE.txt
  doc_url: https://jupyterlab.readthedocs.io/
  dev_url: https://github.com/jupyterlab/language-packs

extra:
  feedstock-name: jupyterlab-language-packs
  recipe-maintainers:
    - blink1073
    - fcollonval
    - goanpeca
    - krassowski
