{% set name = "jupyterlab-language-pack" %}
{% set version = "4.0.post0" %}

package:
  name: {{ name|lower }}-{{ locale|lower }}
  version: {{ version }}

source:
  - folder: ar-SA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ar-SA/{{ name | replace('-', '_') }}_ar_sa-{{ version }}.tar.gz
    sha256: 713c23bd9fc11d5953705ba25df37386424235bd8d34bb60d560547563ff0ffb
  - folder: ca-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ca-ES/{{ name | replace('-', '_') }}_ca_es-{{ version }}.tar.gz
    sha256: db20b42f1ffccb6871b9fa4b5eb62ae648715de928a03ca7e275836ebb5661d9
  - folder: cs-CZ
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-cs-CZ/{{ name | replace('-', '_') }}_cs_cz-{{ version }}.tar.gz
    sha256: c23744f6d86c20f5e3685d1d59aab3ba4b876485b7cda80f0e74d8811cbd7457
  - folder: da-DK
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-da-DK/{{ name | replace('-', '_') }}_da_dk-{{ version }}.tar.gz
    sha256: 0894478309ded1d697b7fb000f2439e9f9ac1914a9d9d734cddb48d0b89eb3df
  - folder: de-DE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-de-DE/{{ name | replace('-', '_') }}_de_de-{{ version }}.tar.gz
    sha256: ae460371a602559c9b45b9cee65a4c750c0be2b303cec2b683b26e518ca6f44b
  - folder: el-GR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-el-GR/{{ name | replace('-', '_') }}_el_gr-{{ version }}.tar.gz
    sha256: 803e3714d974a16846c165b96460f8cc1c1a8a5b56cb4ce9a542c417339c0725
  - folder: es-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-es-ES/{{ name | replace('-', '_') }}_es_es-{{ version }}.tar.gz
    sha256: 81f94e26e7ece451b55b62fd82f30f4e3c23b2a8e5acc26c31083b3ea428dc99
  - folder: et-EE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-et-EE/{{ name | replace('-', '_') }}_et_ee-{{ version }}.tar.gz
    sha256: ea9d7dd974a68da855627a2bbdd77806881b04b376b61c033bd0ce84ad26b984
  - folder: fi-FI
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fi-FI/{{ name | replace('-', '_') }}_fi_fi-{{ version }}.tar.gz
    sha256: 540e0f9fbc8c833037d5abb506b29181e8c1e884851d1cfd2627c9aac5aa90f8
  - folder: fr-FR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fr-FR/{{ name | replace('-', '_') }}_fr_fr-{{ version }}.tar.gz
    sha256: a3d7db0c530a93cc2ecd9102607030d08a2f43a46460c22c3794ef773795f7aa
  - folder: he-IL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-he-IL/{{ name | replace('-', '_') }}_he_il-{{ version }}.tar.gz
    sha256: addd18bb0c731199697b2be18449472aaf88608bae8eb701d21406d84052416e
  - folder: hy-AM
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hy-AM/{{ name | replace('-', '_') }}_hy_am-{{ version }}.tar.gz
    sha256: 33a3de09b284f758bb13c36876dc4829dc11aee7ee1ea57fcd4c847a1203326a
  - folder: hu-HU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hu-HU/{{ name | replace('-', '_') }}_hu_hu-{{ version }}.tar.gz
    sha256: b709fd3fadca71244235d2ed85457aec07efadae16e79f64b4ed342609b032eb
  - folder: id-ID
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-id-ID/{{ name | replace('-', '_') }}_id_id-{{ version }}.tar.gz
    sha256: 1777afc5c13171c0105d2542f00849e8407a9eb697289d6e551aa092d28ed820
  - folder: it-IT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-it-IT/{{ name | replace('-', '_') }}_it_it-{{ version }}.tar.gz
    sha256: e377818d52b1efdfdf3beef292a3b1d551d55e185724e46cceb55ca846a60717
  - folder: ja-JP
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ja-JP/{{ name | replace('-', '_') }}_ja_jp-{{ version }}.tar.gz
    sha256: 9e37113ea395005aedd557f627fc416c9f087d985c9958d4a5126f99e37afaa9
  - folder: ko-KR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ko-KR/{{ name | replace('-', '_') }}_ko_kr-{{ version }}.tar.gz
    sha256: e830ff68b86fb544c4c5ec8eafd7e28b13b585fbbb01a7848a433a9b8996783f
  - folder: lt-LT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-lt-LT/{{ name | replace('-', '_') }}_lt_lt-{{ version }}.tar.gz
    sha256: 0697cff0a35528f57008f4202042a03cbb2f512a01480561b244635c3a6646dd
  - folder: nl-NL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-nl-NL/{{ name | replace('-', '_') }}_nl_nl-{{ version }}.tar.gz
    sha256: 832631d9cfefb3d5034f872e9eb00bc449a90db7fed69de211e4a1c9402e7976
  - folder: no-NO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-no-NO/{{ name | replace('-', '_') }}_no_no-{{ version }}.tar.gz
    sha256: 8d96d86facb67789aba5760f21b035a479d53606f09d2c6d3789884fa98e799a
  - folder: pl-PL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pl-PL/{{ name | replace('-', '_') }}_pl_pl-{{ version }}.tar.gz
    sha256: 5d278bec88a2c500516a6567c63ab5ad0559a276cb5ae40889946e887f897fc8
  - folder: pt-BR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pt-BR/{{ name | replace('-', '_') }}_pt_br-{{ version }}.tar.gz
    sha256: 8e9d4e4ab5b6e02d22b2c424bfd4269724c70fcc6f69e3726a7bbf9af3e6118c
  - folder: ro-RO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ro-RO/{{ name | replace('-', '_') }}_ro_ro-{{ version }}.tar.gz
    sha256: b9e5bdc881394bdd21a121bedb2726c4205e14c0b427e01727f903abb55ce39d
  - folder: ru-RU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ru-RU/{{ name | replace('-', '_') }}_ru_ru-{{ version }}.tar.gz
    sha256: 44587a2d98d9e76009d3e671c7ec4a1e6d84dccdb27c5b5f4c2cdf0d2960c317
  - folder: tr-TR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-tr-TR/{{ name | replace('-', '_') }}_tr_tr-{{ version }}.tar.gz
    sha256: 0f7ca8aad2210955dcea5b7baebcc53c3b8271f846445aec860acb6824696765
  - folder: uk-UA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-uk-UA/{{ name | replace('-', '_') }}_uk_ua-{{ version }}.tar.gz
    sha256: d0e8de8445475a6d350dc62fd9a62e5e1778a22f162d80e1972e97deb43a0ba3
  - folder: vi-VN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-vi-VN/{{ name | replace('-', '_') }}_vi_vn-{{ version }}.tar.gz
    sha256: 9bc62a08757f96b8f6d8ea86484f9fa8d4056f09c01fd014639317eb0f4b666e
  - folder: zh-CN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-CN/{{ name | replace('-', '_') }}_zh_cn-{{ version }}.tar.gz
    sha256: 0c128e53640fdc5e41a4b5f0723fea76819213e2fc5cd9390c2e6cd9c63acbac
  - folder: zh-TW
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-TW/{{ name | replace('-', '_') }}_zh_tw-{{ version }}.tar.gz
    sha256: 51eb6bce5ed2941f64747b2e2b8c1a5f5c875e043640ba8dee0fbfbbb9e915bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install "./{{ locale }}" -vv --no-deps

requirements:
  host:
    - hatchling >=1.4.0
    - jupyterlab-translate >=1.2.0
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab/language-packs
  summary: JupyterLab {{ locale }} Language Pack
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ locale }}/LICENSE.txt
  doc_url: https://jupyterlab.readthedocs.io/
  dev_url: https://github.com/jupyterlab/language-packs

extra:
  feedstock-name: jupyterlab-language-packs
  recipe-maintainers:
    - blink1073
    - fcollonval
    - goanpeca
    - krassowski
