{% set name = "jupyterlab-language-pack" %}
{% set version = "3.2.post4" %}

package:
  name: {{ name|lower }}-{{ locale|lower }}
  version: {{ version }}

source:
  - folder: ar-SA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ar-SA/{{ name }}-ar-SA-{{ version }}.tar.gz
    sha256: bd37294c75b755236999f031a5488cdae635fb849dbbdde9cb459276b923b08c
  - folder: ca-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ca-ES/{{ name }}-ca-ES-{{ version }}.tar.gz
    sha256: e668522a9182f8259823e828f34271a793baf2b20a754ca472302fe89199e514
  - folder: cs-CZ
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-cs-CZ/{{ name }}-cs-CZ-{{ version }}.tar.gz
    sha256: a863722c66694b08471771442377ba092eb8f22f5ebf91951314f52e536f7556
  - folder: da-DK
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-da-DK/{{ name }}-da-DK-{{ version }}.tar.gz
    sha256: c4a61b7681cef9a066fb27257e2998ee08f95daa68c98e15fb9fbb8ccd72d8ef
  - folder: de-DE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-de-DE/{{ name }}-de-DE-{{ version }}.tar.gz
    sha256: 2cc1941c1fa2d79746f145a26b124b6ff329946f00a9bbe3828da098fcf9003f
  - folder: el-GR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-el-GR/{{ name }}-el-GR-{{ version }}.tar.gz
    sha256: 10f3f9798c580fd74bc5534760d38e7cd406a508c7ad847556a93741b6875bab
  - folder: es-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-es-ES/{{ name }}-es-ES-{{ version }}.tar.gz
    sha256: a57bb0586b8b73c43e82eb2662fee17c5133d33204e02bb48f34230e3253b5b4
  - folder: et-EE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-et-EE/{{ name }}-et-EE-{{ version }}.tar.gz
    sha256: 27a14ee01081c173296a78ca9e818f9bb4419d8babb1fb73962b7ce1a3ba3bd8
  - folder: fi-FI
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fi-FI/{{ name }}-fi-FI-{{ version }}.tar.gz
    sha256: 3162526706bb471abe5fbbefda8b807feae0a8a20a3aac262c173a776852944d
  - folder: fr-FR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fr-FR/{{ name }}-fr-FR-{{ version }}.tar.gz
    sha256: 1c5b18daa2c3fe3f6ed3a0ba9dce9ca1dd030856f3ec46a471bcd00bb2fedcdb
  - folder: he-IL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-he-IL/{{ name }}-he-IL-{{ version }}.tar.gz
    sha256: 8ca3f34f33dceb88a0dce290097dbdd79d4616cdc7ce01fe76c5ffe141771e61
  - folder: hy-AM
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hy-AM/{{ name }}-hy-AM-{{ version }}.tar.gz
    sha256: ad41bd2ec286cd21ef94efd5a3aee819e0e4d6cce6e496aed7ecd8b2b5073491
  - folder: hu-HU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hu-HU/{{ name }}-hu-HU-{{ version }}.tar.gz
    sha256: 0e36afb309f607f65d531cf78628102dfa17948479b7ad59b93ffa49406297e6
  - folder: id-ID
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-id-ID/{{ name }}-id-ID-{{ version }}.tar.gz
    sha256: bf874caec5487a233f521dd5068b251136a5069652abb171e3151c785d45e107
  - folder: it-IT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-it-IT/{{ name }}-it-IT-{{ version }}.tar.gz
    sha256: 961df2936353f3839eba91c4f3920e6edb24deb867a835beab17c96a6a671d79
  - folder: ja-JP
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ja-JP/{{ name }}-ja-JP-{{ version }}.tar.gz
    sha256: cfbb8f8ca27d9dd31220755fb3532294fd034dcbc8e96e2ef45cf2eb6ec61a20
  - folder: ko-KR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ko-KR/{{ name }}-ko-KR-{{ version }}.tar.gz
    sha256: 7880d53ebbd7ad34e8190f37080b0d35f24d2ebafedb60550ea44a53c6ea4b83
  - folder: lt-LT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-lt-LT/{{ name }}-lt-LT-{{ version }}.tar.gz
    sha256: b0f9dd3dba33b52b2893750105777b03e53f5b4bd875e22fdda1ae01fc966cf8
  - folder: nl-NL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-nl-NL/{{ name }}-nl-NL-{{ version }}.tar.gz
    sha256: ae51d30688880ee5eae475749ef891e5117e8fab98c480a4e51e6437540da952
  - folder: no-NO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-no-NO/{{ name }}-no-NO-{{ version }}.tar.gz
    sha256: aff86067816fd11cfa4897c01c97e5062ebc6ceb891b6c3adc4ef62cae34ae57
  - folder: pl-PL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pl-PL/{{ name }}-pl-PL-{{ version }}.tar.gz
    sha256: 1f3f07268b12e993876f4259a202daed2fdbd719779d9205d95b456b34b7b750
  - folder: pt-BR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pt-BR/{{ name }}-pt-BR-{{ version }}.tar.gz
    sha256: af1a0523b7fca2944de12fc9d4b10cc4991214745f4daad04b3926ce9c62f873
  - folder: ro-RO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ro-RO/{{ name }}-ro-RO-{{ version }}.tar.gz
    sha256: 5b503b38430b854eb337716b3d2ab8d6883d1fb3a5c507e5d5a99b20f97bad6c
  - folder: ru-RU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ru-RU/{{ name }}-ru-RU-{{ version }}.tar.gz
    sha256: 37eeba98f74da381e430c5dc200591e8d9ba79896f0a7a51618c1cd424ec28b1
  - folder: tr-TR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-tr-TR/{{ name }}-tr-TR-{{ version }}.tar.gz
    sha256: e52d887e883bafc07832b8fc0e6fc22f8e841e588dc6feb40630e761bc9ced8a
  - folder: uk-UA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-uk-UA/{{ name }}-uk-UA-{{ version }}.tar.gz
    sha256: e048cd3b7469c1e8f303d970b37f17fa8f157c62f07ecd4496148d438679bbc7
  - folder: vi-VN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-vi-VN/{{ name }}-vi-VN-{{ version }}.tar.gz
    sha256: 2a85e1dd1d692e87d125ded2c02a9702db49ed12d5a1330eb2ae469a21281525
  - folder: zh-CN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-CN/{{ name }}-zh-CN-{{ version }}.tar.gz
    sha256: fb293e20217ad3aba35d06cca7762d2197567df7c0830386a5f743687d7893a8
  - folder: zh-TW
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-TW/{{ name }}-zh-TW-{{ version }}.tar.gz
    sha256: e5737affe0720cdab58c8562d045d2a52bcc24af71daeee0c8ec72337d07a5ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install "./{{ locale }}" -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab/language-packs
  summary: JupyterLab {{ locale }} Language Pack
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ locale }}/LICENSE.txt
  doc_url: https://jupyterlab.readthedocs.io/
  dev_url: https://github.com/jupyterlab/language-packs

extra:
  feedstock-name: jupyterlab-language-packs
  recipe-maintainers:
    - blink1073
    - fcollonval
    - goanpeca
    - krassowski
