{% set name = "jupyterlab-language-pack" %}
{% set version = "3.4.post5" %}

package:
  name: {{ name|lower }}-{{ locale|lower }}
  version: {{ version }}

source:
  - folder: ar-SA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ar-SA/{{ name }}-ar-SA-{{ version }}.tar.gz
    sha256: 159ae1b9344dc235fb2cd09187904cf3a865b790723bf43c4088f7502da812ab
  - folder: ca-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ca-ES/{{ name }}-ca-ES-{{ version }}.tar.gz
    sha256: 3be059a0f93158f1c7c8795543121ff4b2a9a3b9b6b43bc176d579de23c0e9ab
  - folder: cs-CZ
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-cs-CZ/{{ name }}-cs-CZ-{{ version }}.tar.gz
    sha256: 31b0756b4bdf66a6fd71421a65482991d298b13b42b9450ffaf982d564d2363e
  - folder: da-DK
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-da-DK/{{ name }}-da-DK-{{ version }}.tar.gz
    sha256: ca6a9e15d379698b6c84364aa08ffe38c48ea7d6ede2c286a571e3ebc81f3d74
  - folder: de-DE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-de-DE/{{ name }}-de-DE-{{ version }}.tar.gz
    sha256: d0f246c9d033599284b906a50a01447f149d53b5d92da956b8d28786a5614e5f
  - folder: el-GR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-el-GR/{{ name }}-el-GR-{{ version }}.tar.gz
    sha256: f0c160f780d45bcead8e03be98f3a9bc4e11f832d44436e162608882bed044bb
  - folder: es-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-es-ES/{{ name }}-es-ES-{{ version }}.tar.gz
    sha256: ebc8f771e1f1fbb50e9adb0fcf0575b54661bae4a55f05e999ff050dd278907b
  - folder: et-EE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-et-EE/{{ name }}-et-EE-{{ version }}.tar.gz
    sha256: 15f5c2ef245503f3ecc05dcb6729b2456c885480022223b7cb5ba1e48cb24158
  - folder: fi-FI
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fi-FI/{{ name }}-fi-FI-{{ version }}.tar.gz
    sha256: fe949d0b4495ba8ac2c54da8b0171633b0213618c4df6234e34f469f509120ed
  - folder: fr-FR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fr-FR/{{ name }}-fr-FR-{{ version }}.tar.gz
    sha256: f87fd02183c3d5a3e72b6e44b34ac4acd9b43571ad36d38f40f3d0693fdcd570
  - folder: he-IL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-he-IL/{{ name }}-he-IL-{{ version }}.tar.gz
    sha256: 0b8e0d1f4ea1158b37c9a6fa766b66638d4b979146049c6b54bbfea6adf48542
  - folder: hy-AM
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hy-AM/{{ name }}-hy-AM-{{ version }}.tar.gz
    sha256: dc93bf20004a29eb247e07a8bb9b54904b07b6b02c4a58661f38905ca0dcc497
  - folder: hu-HU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hu-HU/{{ name }}-hu-HU-{{ version }}.tar.gz
    sha256: c5b850d9e25c36b1896772247ab45ed5804ab666cc7467c8df36b03d36b5e128
  - folder: id-ID
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-id-ID/{{ name }}-id-ID-{{ version }}.tar.gz
    sha256: 790346a8d7ab4808800cd8f0e2d92c989a04e356aec1ed26fc326fc7142ee259
  - folder: it-IT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-it-IT/{{ name }}-it-IT-{{ version }}.tar.gz
    sha256: bdbf2d1e7e49d87e5799a1a708a5e91cc534a09bcb88ec0554ce16d313a7358f
  - folder: ja-JP
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ja-JP/{{ name }}-ja-JP-{{ version }}.tar.gz
    sha256: bc2a468df164fb10db80fc0d97f0b7fb691a2071c915d3f7c456704a0293a536
  - folder: ko-KR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ko-KR/{{ name }}-ko-KR-{{ version }}.tar.gz
    sha256: b41f2b5e33c1ba20e0db14e1d9745592bb7f41c7017e7d98d8f4944c83c9bde8
  - folder: lt-LT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-lt-LT/{{ name }}-lt-LT-{{ version }}.tar.gz
    sha256: 13fbb20800ab2dcb969f23d0038d1d6b878d7614ce985b693dce3051e5008ffe
  - folder: nl-NL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-nl-NL/{{ name }}-nl-NL-{{ version }}.tar.gz
    sha256: 214882578bc485122e26073d9fd4a3b007136c85cfbb38557db238d9536b0a85
  - folder: no-NO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-no-NO/{{ name }}-no-NO-{{ version }}.tar.gz
    sha256: 185f7eba991e44e4c8b0387dae7fb810288299319126398833b75a3620e45bd0
  - folder: pl-PL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pl-PL/{{ name }}-pl-PL-{{ version }}.tar.gz
    sha256: bc1a9cdfdf18534ad3d28d3e7f07feec9a1d5819828e40eab9b6bdc71eed6d1d
  - folder: pt-BR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pt-BR/{{ name }}-pt-BR-{{ version }}.tar.gz
    sha256: 59fd8f3c483186e814604c1e18dc1044570581aaceb6bcc9ecf1b2c2296eb4f3
  - folder: ro-RO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ro-RO/{{ name }}-ro-RO-{{ version }}.tar.gz
    sha256: 9e3a0a325bebd30945eb45b7c5c23461bdc909009d9b1ea911e2b9302ddfa562
  - folder: ru-RU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ru-RU/{{ name }}-ru-RU-{{ version }}.tar.gz
    sha256: aff9b4612ea5e2d8de30f2117a2e43c33c9723a563478f19296b0a8a7438a8dc
  - folder: tr-TR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-tr-TR/{{ name }}-tr-TR-{{ version }}.tar.gz
    sha256: 316232895dfcd6bf1c5f6fa70593832de9cc65d9b59c328b0c58f986e7d00440
  - folder: uk-UA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-uk-UA/{{ name }}-uk-UA-{{ version }}.tar.gz
    sha256: 8f0f98c0494bdb713d365b73dd73a12cb395c5281e06df541e1470358a0af557
  - folder: vi-VN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-vi-VN/{{ name }}-vi-VN-{{ version }}.tar.gz
    sha256: 9d925cf866416de904495d5472d4d61745e37b4d5931d026af1491bcd54a3b5b
  - folder: zh-CN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-CN/{{ name }}-zh-CN-{{ version }}.tar.gz
    sha256: 4521ea64e1bffc91c4e9476f48fd1101793cca2811fea79a63664c036c0bf638
  - folder: zh-TW
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-TW/{{ name }}-zh-TW-{{ version }}.tar.gz
    sha256: 18763501af95036cce2ac49f950f6c165993639549955240047d7f2dcbd52583

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install "./{{ locale }}" -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab/language-packs
  summary: JupyterLab {{ locale }} Language Pack
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ locale }}/LICENSE.txt
  doc_url: https://jupyterlab.readthedocs.io/
  dev_url: https://github.com/jupyterlab/language-packs

extra:
  feedstock-name: jupyterlab-language-packs
  recipe-maintainers:
    - blink1073
    - fcollonval
    - goanpeca
    - krassowski
