{% set name = "jupyterlab-language-pack" %}
{% set version = "4.5.post2" %}

package:
  name: {{ name|lower }}-{{ locale|lower }}
  version: {{ version }}

source:
  - folder: ar-SA
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ar-SA/{{ name | replace('-', '_') }}_ar_sa-{{ version }}.tar.gz
    sha256: b54c7b4404720c96031a6c16b8918a75e355ac8600970c6caf5751a06f335295
  - folder: ca-ES
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ca-ES/{{ name | replace('-', '_') }}_ca_es-{{ version }}.tar.gz
    sha256: 3d4c4a622a2865e679351c5774ce7e6a78bbe99b04298b5397b8bd7e291f5662
  - folder: cs-CZ
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-cs-CZ/{{ name | replace('-', '_') }}_cs_cz-{{ version }}.tar.gz
    sha256: 801be887ccf2d7031a55caad0f9a6f9896664977cb8c355cd97b151c37fcf897
  - folder: da-DK
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-da-DK/{{ name | replace('-', '_') }}_da_dk-{{ version }}.tar.gz
    sha256: 170b38f11b62296251529d7b5dfcaeb4263f571d8db145652643b047d2cc9422
  - folder: de-DE
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-de-DE/{{ name | replace('-', '_') }}_de_de-{{ version }}.tar.gz
    sha256: 6c0bfbae0eb87c34a8136db03b9b011d3c8e6ae7b9d45cde388166386e744b5a
  - folder: el-GR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-el-GR/{{ name | replace('-', '_') }}_el_gr-{{ version }}.tar.gz
    sha256: bef36f019b864b7ee1a730ccfd29744d8dabdd1c88e7233c370c6c8af1173be6
  - folder: es-ES
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-es-ES/{{ name | replace('-', '_') }}_es_es-{{ version }}.tar.gz
    sha256: a2bb877fc9c1cd9e5190d7be5bf9f10b062f84af4eb796ae6fb2754e410991cb
  - folder: et-EE
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-et-EE/{{ name | replace('-', '_') }}_et_ee-{{ version }}.tar.gz
    sha256: 6b43f1a033c4ba6fc271343ed4c67a73f6a4418d246917c3dfd18b6c5e2f2b92
  - folder: fi-FI
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-fi-FI/{{ name | replace('-', '_') }}_fi_fi-{{ version }}.tar.gz
    sha256: 39d7cd22d28b2061865a76457db0c93669846747f1aa9cda981e079200b8e81d
  - folder: fr-FR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-fr-FR/{{ name | replace('-', '_') }}_fr_fr-{{ version }}.tar.gz
    sha256: ca0502ffee86e78dd519bf23424101aa572832171079505febcc63b827d3c7ed
  - folder: he-IL
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-he-IL/{{ name | replace('-', '_') }}_he_il-{{ version }}.tar.gz
    sha256: c78248c3f622311ab29423c8697efc969cf2c22b2ffc73e36cb42c49bbe419b6
  - folder: hy-AM
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-hy-AM/{{ name | replace('-', '_') }}_hy_am-{{ version }}.tar.gz
    sha256: 39a73f76232f90d63c938f4950171d4cad7392ec3bebec64378a7d4cfa2fca3c
  - folder: hu-HU
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-hu-HU/{{ name | replace('-', '_') }}_hu_hu-{{ version }}.tar.gz
    sha256: 118ae576f108a2d5619b4343ade6b2681f5ae8b0be7d6b5cf078acef165abbad
  - folder: id-ID
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-id-ID/{{ name | replace('-', '_') }}_id_id-{{ version }}.tar.gz
    sha256: 0ec4ff5240a1de678fcb9197ab8485724f268261aa562a112fdb688d400e143b
  - folder: it-IT
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-it-IT/{{ name | replace('-', '_') }}_it_it-{{ version }}.tar.gz
    sha256: 8ea49ecf0e2d0484f0d09354ad65ea5f50b421b5c4188218799059b403b97977
  - folder: ja-JP
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ja-JP/{{ name | replace('-', '_') }}_ja_jp-{{ version }}.tar.gz
    sha256: 8b11b604305225b964cb582ce997fdeae4389a05d900ca16fd018417e170942c
  - folder: ko-KR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ko-KR/{{ name | replace('-', '_') }}_ko_kr-{{ version }}.tar.gz
    sha256: e9d9b7bfb1ee54036d296c302406afdd2d582136ecd8ca07966fc82f298ae2a8
  - folder: lt-LT
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-lt-LT/{{ name | replace('-', '_') }}_lt_lt-{{ version }}.tar.gz
    sha256: 67f57991357386209ed86a02a7e5fbe181e113eb7d53da753e5f33fe7941b4a9
  - folder: nl-NL
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-nl-NL/{{ name | replace('-', '_') }}_nl_nl-{{ version }}.tar.gz
    sha256: 93cedde07e9a718619956fda0a77bdddc9787222a3704816f32fa7bf33165344
  - folder: no-NO
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-no-NO/{{ name | replace('-', '_') }}_no_no-{{ version }}.tar.gz
    sha256: c94f43aab82238167f33213ad73461a4ec74ea945126a001647e9cba5a31190c
  - folder: pl-PL
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-pl-PL/{{ name | replace('-', '_') }}_pl_pl-{{ version }}.tar.gz
    sha256: e312842e7bdee9174e4158150884f05ec053c172bb04df1dafc30e105ca361f0
  - folder: pt-BR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-pt-BR/{{ name | replace('-', '_') }}_pt_br-{{ version }}.tar.gz
    sha256: cc3ef83f0542dc7f8ed01581db5fc824ff8faddf50738c47252852e75d344c02
  - folder: ro-RO
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ro-RO/{{ name | replace('-', '_') }}_ro_ro-{{ version }}.tar.gz
    sha256: 4b9477079be1d6234a3b26b542a61512598028d6891910f2ecc4a63e97ca3dc3
  - folder: ru-RU
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ru-RU/{{ name | replace('-', '_') }}_ru_ru-{{ version }}.tar.gz
    sha256: 1953de74f6bbf21ed8209985bcc082f2cb98986fcd95ced16903e12814a1e407
  - folder: tr-TR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-tr-TR/{{ name | replace('-', '_') }}_tr_tr-{{ version }}.tar.gz
    sha256: f198a75fe06999741eab24b375021127d5249d4e9d86a615e435ab160ff37395
  - folder: uk-UA
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-uk-UA/{{ name | replace('-', '_') }}_uk_ua-{{ version }}.tar.gz
    sha256: c2bd94953597dc3f1406e04a4a00129115a7ffac6ad31c303c2b306838cc82ab
  - folder: vi-VN
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-vi-VN/{{ name | replace('-', '_') }}_vi_vn-{{ version }}.tar.gz
    sha256: 69ee4d6af745cfd8d9fe11e75bb9781db0cc604d22bf125d70794eee16f75fab
  - folder: zh-CN
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-zh-CN/{{ name | replace('-', '_') }}_zh_cn-{{ version }}.tar.gz
    sha256: 42e4133e70ebe9935955d06c10886afebe0c06b4870b146b228298c032f15b11
  - folder: zh-TW
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-zh-TW/{{ name | replace('-', '_') }}_zh_tw-{{ version }}.tar.gz
    sha256: 26bc5b6d50b26e1640fda379ccb25bdfa02be06c8bc9ea267648ca620b40fde5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install "./{{ locale }}" -vv --no-deps

requirements:
  host:
    - hatchling >=1.4.0
    - jupyterlab-translate >=1.2.0
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab/language-packs
  summary: JupyterLab {{ locale }} Language Pack
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ locale }}/LICENSE.txt
  doc_url: https://jupyterlab.readthedocs.io/
  dev_url: https://github.com/jupyterlab/language-packs

extra:
  feedstock-name: jupyterlab-language-packs
  recipe-maintainers:
    - blink1073
    - fcollonval
    - goanpeca
    - krassowski
