{% set name = "jupyterlab-language-pack" %}
{% set version = "3.2.post5" %}

package:
  name: {{ name|lower }}-{{ locale|lower }}
  version: {{ version }}

source:
  - folder: ar-SA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ar-SA/{{ name }}-ar-SA-{{ version }}.tar.gz
    sha256: 9f3d1b22a4872bdb43f4c1897e6db5168ecafb4a23f34d52f28289fb14b397ed
  - folder: ca-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ca-ES/{{ name }}-ca-ES-{{ version }}.tar.gz
    sha256: 397e9f2dca4ea839ab2c749379869cb513d53d57c4635ef895cf1cc09f1606c7
  - folder: cs-CZ
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-cs-CZ/{{ name }}-cs-CZ-{{ version }}.tar.gz
    sha256: f7e9761c47b93eca5804e3a3def3068265eef30dcfa24e2dc0ad9c6850256502
  - folder: da-DK
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-da-DK/{{ name }}-da-DK-{{ version }}.tar.gz
    sha256: 038ad9940765e2b4dd6f18285afcce59035ddcd1ae22e6b74f3854a587964fc3
  - folder: de-DE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-de-DE/{{ name }}-de-DE-{{ version }}.tar.gz
    sha256: 3942f85dff1ac39e577d4a22ca00292dcfcfe043a826038e3a12893fcb8ebb85
  - folder: el-GR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-el-GR/{{ name }}-el-GR-{{ version }}.tar.gz
    sha256: d0db31e4c64da9adb3dacc35cd5737215a8a70e331c4597f0bc4ac53fbf0ef95
  - folder: es-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-es-ES/{{ name }}-es-ES-{{ version }}.tar.gz
    sha256: 5d6d15b7b8b0455f50a0a0367355ae226ca0491c50ea5b572bb4e8de8926db8e
  - folder: et-EE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-et-EE/{{ name }}-et-EE-{{ version }}.tar.gz
    sha256: b00844033134613803274db460b7f1553b0c3513fe0b39497c6457c945b5e265
  - folder: fi-FI
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fi-FI/{{ name }}-fi-FI-{{ version }}.tar.gz
    sha256: 0ac90a71231a3fae61f7825fca5875e642522243a89d4021c25d6d8fa9271c24
  - folder: fr-FR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fr-FR/{{ name }}-fr-FR-{{ version }}.tar.gz
    sha256: b243625aa56e0cb2921855c67994ccd19d9883b7dc90c8ccc3f68746d0bb8ff2
  - folder: he-IL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-he-IL/{{ name }}-he-IL-{{ version }}.tar.gz
    sha256: 106ed8acb820f93902ae990b234dc52b5297993d5f2449a16789084c80377d01
  - folder: hy-AM
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hy-AM/{{ name }}-hy-AM-{{ version }}.tar.gz
    sha256: aa494b9c27adb5fd322fed8812603fed383d5bc1efeec732b2c44698ec42cfb6
  - folder: hu-HU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hu-HU/{{ name }}-hu-HU-{{ version }}.tar.gz
    sha256: c425f09fa5deb2b6bc8315191ac178297087f0707a00d7692f17e95683cac91c
  - folder: id-ID
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-id-ID/{{ name }}-id-ID-{{ version }}.tar.gz
    sha256: 5be5ddcc16608c05aa8be2ba31350c3d2b6dc77d4c34b25d9d81d42904c25b02
  - folder: it-IT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-it-IT/{{ name }}-it-IT-{{ version }}.tar.gz
    sha256: 0d783f470dea87d30090d99d8e4c1a81966aac5a225750fdbd47bba699953713
  - folder: ja-JP
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ja-JP/{{ name }}-ja-JP-{{ version }}.tar.gz
    sha256: 8412d90abbd19e4f1df87b6f0eeffad4c3ecad3d71bf1ce500bc58ece821475d
  - folder: ko-KR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ko-KR/{{ name }}-ko-KR-{{ version }}.tar.gz
    sha256: a86bb5bc52d2656bfd8d65c14d98256c983d521ea2d72448e99d35ee41308c26
  - folder: lt-LT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-lt-LT/{{ name }}-lt-LT-{{ version }}.tar.gz
    sha256: 2514e31b84bf8bd6c4aea09a4ab920724d885c59aafd8c0cbaad623d3060b030
  - folder: nl-NL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-nl-NL/{{ name }}-nl-NL-{{ version }}.tar.gz
    sha256: dac52354e82ec85cca3e650a724d3c7d087636b322b385864028c534c27be450
  - folder: no-NO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-no-NO/{{ name }}-no-NO-{{ version }}.tar.gz
    sha256: c928511a350141ffe2e79558dcdaf809a388b32d3e98691b510db755ea3933a1
  - folder: pl-PL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pl-PL/{{ name }}-pl-PL-{{ version }}.tar.gz
    sha256: 298a4e164bb164d3c3e45a7e1cfb1a56a9de8a063dd77541ba5bae2af44146a1
  - folder: pt-BR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pt-BR/{{ name }}-pt-BR-{{ version }}.tar.gz
    sha256: ab0928970ac84ac5bd789c634a7cbf950dc4a0accbb07ba8c2e4aae8bf25046f
  - folder: ro-RO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ro-RO/{{ name }}-ro-RO-{{ version }}.tar.gz
    sha256: 5fcb583d0b02d543674c80bbbadf7b1ee46e43881e342a6e3ff5ca8620f994b4
  - folder: ru-RU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ru-RU/{{ name }}-ru-RU-{{ version }}.tar.gz
    sha256: 8545f6bb442b56213cf5fd65b84c664876e615eb91b0a654c9b312c3d935eba4
  - folder: tr-TR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-tr-TR/{{ name }}-tr-TR-{{ version }}.tar.gz
    sha256: 97b94687255ddf8606e6d95b586cd2087ab15070ef9155b7e1c8910bb7ef1c8f
  - folder: uk-UA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-uk-UA/{{ name }}-uk-UA-{{ version }}.tar.gz
    sha256: c225ba3ae01fd9bdaa101d8c772487075da8b26d82dc59a9e7bbe7d227304b5a
  - folder: vi-VN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-vi-VN/{{ name }}-vi-VN-{{ version }}.tar.gz
    sha256: 5b09dd40b8ecf5ad0c1f0af72aeff154bc1f83ee124ea367dc04af9f11723d91
  - folder: zh-CN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-CN/{{ name }}-zh-CN-{{ version }}.tar.gz
    sha256: ca20861d4f78314c63ec08d594571b07fb3fcde090f37ab563ff4d995d140703
  - folder: zh-TW
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-TW/{{ name }}-zh-TW-{{ version }}.tar.gz
    sha256: 3cab5afbc9008f161a52f522ec2b1dde9f990caa07145b3f42209f9da09ba87f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install "./{{ locale }}" -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab/language-packs
  summary: JupyterLab {{ locale }} Language Pack
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ locale }}/LICENSE.txt
  doc_url: https://jupyterlab.readthedocs.io/
  dev_url: https://github.com/jupyterlab/language-packs

extra:
  feedstock-name: jupyterlab-language-packs
  recipe-maintainers:
    - blink1073
    - fcollonval
    - goanpeca
    - krassowski
