{% set name = "jupyterlab-language-pack" %}
{% set version = "4.4.post1" %}

package:
  name: {{ name|lower }}-{{ locale|lower }}
  version: {{ version }}

source:
  - folder: ar-SA
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ar-SA/{{ name | replace('-', '_') }}_ar_sa-{{ version }}.tar.gz
    sha256: 1d685f9b2902bbd2d1a1391dbf589847187e6440e64cfa4af28bb0aa434c11ca
  - folder: ca-ES
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ca-ES/{{ name | replace('-', '_') }}_ca_es-{{ version }}.tar.gz
    sha256: f9685b460633e95883bd4b9c1f5e524a282b9bb4db0513c805634458cae55d1f
  - folder: cs-CZ
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-cs-CZ/{{ name | replace('-', '_') }}_cs_cz-{{ version }}.tar.gz
    sha256: 6ced8c8de8a0b09113e7bd4aeece4f692198c2fabbe4516c1d42f7928bbfb470
  - folder: da-DK
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-da-DK/{{ name | replace('-', '_') }}_da_dk-{{ version }}.tar.gz
    sha256: 60f60edb5824c1482b4d584596404560788dfc3c33f7c2567c0a142fa609d6eb
  - folder: de-DE
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-de-DE/{{ name | replace('-', '_') }}_de_de-{{ version }}.tar.gz
    sha256: 385c83600c58b477cc2a83d2eda9a000f514b2b0e9b1b66d51472e0420436fdc
  - folder: el-GR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-el-GR/{{ name | replace('-', '_') }}_el_gr-{{ version }}.tar.gz
    sha256: 5f486638cb794c72d3fde33967ca77389d5bfeb29b5b3b981f592887a5e24f29
  - folder: es-ES
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-es-ES/{{ name | replace('-', '_') }}_es_es-{{ version }}.tar.gz
    sha256: 0b596eb88373ae1ba1549744bd10c1ca55603ca9efc43b14d91358439865cea3
  - folder: et-EE
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-et-EE/{{ name | replace('-', '_') }}_et_ee-{{ version }}.tar.gz
    sha256: 78c280d65fbac62275f354dbdb4fa95f638cf34425f2d7da449ab3effe293162
  - folder: fi-FI
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-fi-FI/{{ name | replace('-', '_') }}_fi_fi-{{ version }}.tar.gz
    sha256: d5fa28759ef4aea81068553b5d1e14610ff2a4914db90f92815ef0c71be13af0
  - folder: fr-FR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-fr-FR/{{ name | replace('-', '_') }}_fr_fr-{{ version }}.tar.gz
    sha256: e04d5b7768463e0c011ba928364abb49f58abdad016a066431da975523b454b3
  - folder: he-IL
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-he-IL/{{ name | replace('-', '_') }}_he_il-{{ version }}.tar.gz
    sha256: 93c2ed906cba22049f3825f43e1c03edafb851c526436849b315d56f53283418
  - folder: hy-AM
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-hy-AM/{{ name | replace('-', '_') }}_hy_am-{{ version }}.tar.gz
    sha256: 3f4bac6a3839f1282bfe08d4342ebf67a3f950fce8b777f2e0290f4d185a1405
  - folder: hu-HU
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-hu-HU/{{ name | replace('-', '_') }}_hu_hu-{{ version }}.tar.gz
    sha256: 81ffae052a915dc416953758c18885848df4a412b90eb509bf8212ee3c69d00b
  - folder: id-ID
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-id-ID/{{ name | replace('-', '_') }}_id_id-{{ version }}.tar.gz
    sha256: 0b083b57640ceafccafbaa957eccab5bb8530525c2bdecc4f9cd4abddb609341
  - folder: it-IT
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-it-IT/{{ name | replace('-', '_') }}_it_it-{{ version }}.tar.gz
    sha256: 775d3c6ca893bc374b173e7b2c72808ffd2e1a19e1f11cdb9e154a4c95250660
  - folder: ja-JP
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ja-JP/{{ name | replace('-', '_') }}_ja_jp-{{ version }}.tar.gz
    sha256: 7032f856b863908d438864430837d2533eb32acc85e417b1774528ca18811693
  - folder: ko-KR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ko-KR/{{ name | replace('-', '_') }}_ko_kr-{{ version }}.tar.gz
    sha256: 0b1ecceb082e0f5fe9674b5d231efba568990098a01ec4267b9c69d2dcff1e99
  - folder: lt-LT
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-lt-LT/{{ name | replace('-', '_') }}_lt_lt-{{ version }}.tar.gz
    sha256: ffa6076946cc84c602c2e6ba281d2efed651f873b47a5a53f42b4f38c22c0aaa
  - folder: nl-NL
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-nl-NL/{{ name | replace('-', '_') }}_nl_nl-{{ version }}.tar.gz
    sha256: c8ac3503a4a888b92fd3ae5a58028e495aec6825710d47418c44e438b0cf5b15
  - folder: no-NO
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-no-NO/{{ name | replace('-', '_') }}_no_no-{{ version }}.tar.gz
    sha256: a67bc73e74818a069dc72a070b3560282b98ef9b3292f0cb74ac251a8aee1815
  - folder: pl-PL
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-pl-PL/{{ name | replace('-', '_') }}_pl_pl-{{ version }}.tar.gz
    sha256: 9bd6c2a9c8eb3af19670fa8a2552d0899cdba38071d19eabf606c043b2934836
  - folder: pt-BR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-pt-BR/{{ name | replace('-', '_') }}_pt_br-{{ version }}.tar.gz
    sha256: 1a68e68e91487f4e991eea8ebe1f9c49d4ac81e9fda18dc78f7aa0d67f1736ac
  - folder: ro-RO
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ro-RO/{{ name | replace('-', '_') }}_ro_ro-{{ version }}.tar.gz
    sha256: 89457163f2ee3e5841eeca37d970e8e65da7ca315346693b58df21ac805b4f0b
  - folder: ru-RU
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-ru-RU/{{ name | replace('-', '_') }}_ru_ru-{{ version }}.tar.gz
    sha256: 9c2148b98ba8ded43ab84e4f7ff9c2064e171f45ca1e7925480fc82a6275691e
  - folder: tr-TR
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-tr-TR/{{ name | replace('-', '_') }}_tr_tr-{{ version }}.tar.gz
    sha256: 20062e2d6231e43a7685b60b167cd630b51a5a82b200eb6a092535bb55b346d4
  - folder: uk-UA
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-uk-UA/{{ name | replace('-', '_') }}_uk_ua-{{ version }}.tar.gz
    sha256: f9657fe00cfe297754db470df68e2d6885359778ab25e5b04e8936bf315daa87
  - folder: vi-VN
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-vi-VN/{{ name | replace('-', '_') }}_vi_vn-{{ version }}.tar.gz
    sha256: f61c6fc4f4faa543488f2598055abf389d91d358eafe3c6bc4f990218e8b4d3c
  - folder: zh-CN
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-zh-CN/{{ name | replace('-', '_') }}_zh_cn-{{ version }}.tar.gz
    sha256: 299e78833a6ac2fa26427a903564c33cd3afe91ab59a9e96dc75c3e3ca10ce85
  - folder: zh-TW
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-zh-TW/{{ name | replace('-', '_') }}_zh_tw-{{ version }}.tar.gz
    sha256: 21c8b1cc8500bee288c265318c1315ddbdf15481339f7b107e6d28101c19c27f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install "./{{ locale }}" -vv --no-deps

requirements:
  host:
    - hatchling >=1.4.0
    - jupyterlab-translate >=1.2.0
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab/language-packs
  summary: JupyterLab {{ locale }} Language Pack
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ locale }}/LICENSE.txt
  doc_url: https://jupyterlab.readthedocs.io/
  dev_url: https://github.com/jupyterlab/language-packs

extra:
  feedstock-name: jupyterlab-language-packs
  recipe-maintainers:
    - blink1073
    - fcollonval
    - goanpeca
    - krassowski
