{% set name = "jupyterlab-language-pack" %}
{% set version = "3.4.post4" %}

package:
  name: {{ name|lower }}-{{ locale|lower }}
  version: {{ version }}

source:
  - folder: ar-SA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ar-SA/{{ name }}-ar-SA-{{ version }}.tar.gz
    sha256: 3e916c04b6486bad2c5b9ea2f30b00d9cd2017c2349e291c91a7926d92e18a53
  - folder: ca-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ca-ES/{{ name }}-ca-ES-{{ version }}.tar.gz
    sha256: 0f70d11f7cb97f94189d28ebaa6cab4ce46d2928cb7d965faf251105265750aa
  - folder: cs-CZ
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-cs-CZ/{{ name }}-cs-CZ-{{ version }}.tar.gz
    sha256: 469943d27e210cb2aeb0cd38dc4d70e3e08db45ee5e5fe02fe3b9985cc7e2a65
  - folder: da-DK
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-da-DK/{{ name }}-da-DK-{{ version }}.tar.gz
    sha256: deef18c3cecf8de811841cc4521a1942e379f09dc75e251081fa0482602deff7
  - folder: de-DE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-de-DE/{{ name }}-de-DE-{{ version }}.tar.gz
    sha256: 7276d16f57414c04f5a439fe5a6e6b7627d39fd37c1c42e45597510d54e8a3c7
  - folder: el-GR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-el-GR/{{ name }}-el-GR-{{ version }}.tar.gz
    sha256: 14b85d4c41c50c201f6c05d53a3e5e3a1178b2a6408a54deb018034a11236121
  - folder: es-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-es-ES/{{ name }}-es-ES-{{ version }}.tar.gz
    sha256: d950abe4f8094a146c9c49f1debd71195b0aa575ddcb213ff0c87b470ed0f6c7
  - folder: et-EE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-et-EE/{{ name }}-et-EE-{{ version }}.tar.gz
    sha256: 26a3dc33dfd206d3edca64c15d9f7889b5535c05e1c1c885723fa30154fa207b
  - folder: fi-FI
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fi-FI/{{ name }}-fi-FI-{{ version }}.tar.gz
    sha256: c2478c1f03743e717f7708b13f145360aa8a52c3e626b08da1ed1dd692410ca8
  - folder: fr-FR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fr-FR/{{ name }}-fr-FR-{{ version }}.tar.gz
    sha256: d4299587257802b5235a67b8115988f1ac1d7d00a9dfb50df782708250658b2f
  - folder: he-IL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-he-IL/{{ name }}-he-IL-{{ version }}.tar.gz
    sha256: dc8dce69a2982bced8c07c8a57b622257014c4c5c4d6d1857dcd540e4c28e5f8
  - folder: hy-AM
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hy-AM/{{ name }}-hy-AM-{{ version }}.tar.gz
    sha256: d75ae213b948b282fe47770d0208f56819d3c80d77d4d9527dc75f6b7037c24a
  - folder: hu-HU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hu-HU/{{ name }}-hu-HU-{{ version }}.tar.gz
    sha256: 95b7602f1cc46d6c1fa15e7f8e1820a43caf0d984c2ddd3d85adfc287f510002
  - folder: id-ID
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-id-ID/{{ name }}-id-ID-{{ version }}.tar.gz
    sha256: ee7b4db56a6216308933ac3e3802aac5f6f197f284050e5d687c40e5fbd992b5
  - folder: it-IT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-it-IT/{{ name }}-it-IT-{{ version }}.tar.gz
    sha256: e1439abcc63af57c22a7a9e916a8fc1f342f758f6a7faae860f0aa8518c948d0
  - folder: ja-JP
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ja-JP/{{ name }}-ja-JP-{{ version }}.tar.gz
    sha256: e0877f21498abe4caf3336dfe3baac7b92611c7333764333ba8147b9989c88f2
  - folder: ko-KR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ko-KR/{{ name }}-ko-KR-{{ version }}.tar.gz
    sha256: 325320022ad99ac02be6b43b1a5e4287c0198e989c94b8e3a22c5979f9d248cc
  - folder: lt-LT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-lt-LT/{{ name }}-lt-LT-{{ version }}.tar.gz
    sha256: d1b74e3e3962e68fdaba6beffae4327e415a7c5a59d4f75f1cb59469166045de
  - folder: nl-NL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-nl-NL/{{ name }}-nl-NL-{{ version }}.tar.gz
    sha256: 94cc478aa68d0da12e5a17e6aba374137df2155e3a797132bf94c3f143048602
  - folder: no-NO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-no-NO/{{ name }}-no-NO-{{ version }}.tar.gz
    sha256: 1d3bb827ef17b4f358d3ab990b8a7ab3bf5667b4b9da0a332fd10966b4a5547c
  - folder: pl-PL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pl-PL/{{ name }}-pl-PL-{{ version }}.tar.gz
    sha256: 6dce3fef38a9b3bf1dbcc63b9448bf53789c19d1660b3be0f3d0bc5b6d082c6f
  - folder: pt-BR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pt-BR/{{ name }}-pt-BR-{{ version }}.tar.gz
    sha256: 2fb01d356043e6bbdcc04fff7818e476f25e9894e4e10ffe606ee2fd23b4ff86
  - folder: ro-RO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ro-RO/{{ name }}-ro-RO-{{ version }}.tar.gz
    sha256: f2792473899989d4328d2e6eb3dcd51ab45dd630b576ff4dd9e1bdbbd5d57ff3
  - folder: ru-RU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ru-RU/{{ name }}-ru-RU-{{ version }}.tar.gz
    sha256: 60279c50dedd337e817d169d0ebe1b3edd2d3e72f13b75fe2b63260c0200b2bc
  - folder: tr-TR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-tr-TR/{{ name }}-tr-TR-{{ version }}.tar.gz
    sha256: b1826ec378755bc0588511cfaa8df4201760e77ea038858abd5231cb31723029
  - folder: uk-UA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-uk-UA/{{ name }}-uk-UA-{{ version }}.tar.gz
    sha256: c3a07a76c2f039f95c1ed0866d11b00d297326e3519f7538388d007c882d12fa
  - folder: vi-VN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-vi-VN/{{ name }}-vi-VN-{{ version }}.tar.gz
    sha256: 1435aed2ad28026a2cc761a6f83e13c05e26a95a1dc3abc8c6eaf19797c07063
  - folder: zh-CN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-CN/{{ name }}-zh-CN-{{ version }}.tar.gz
    sha256: 6125f400366d00a02e1949d18e57c32a55608ee7c36f3e4f4d67681626c3ca44
  - folder: zh-TW
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-TW/{{ name }}-zh-TW-{{ version }}.tar.gz
    sha256: 295bf84906683be6610b89400cbacf1b79433d80220962f521c8aa18d732cc8e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install "./{{ locale }}" -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab/language-packs
  summary: JupyterLab {{ locale }} Language Pack
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ locale }}/LICENSE.txt
  doc_url: https://jupyterlab.readthedocs.io/
  dev_url: https://github.com/jupyterlab/language-packs

extra:
  feedstock-name: jupyterlab-language-packs
  recipe-maintainers:
    - blink1073
    - fcollonval
    - goanpeca
    - krassowski
