{% set name = "jupyterlab-language-pack" %}
{% set version = "3.2.post7" %}

package:
  name: {{ name|lower }}-{{ locale|lower }}
  version: {{ version }}

source:
  - folder: ar-SA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ar-SA/{{ name }}-ar-SA-{{ version }}.tar.gz
    sha256: 8186ba72201ea67baa1b6fef9d2dc44c4d9d62e65fd5d26c10e539324e3b48f1
  - folder: ca-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ca-ES/{{ name }}-ca-ES-{{ version }}.tar.gz
    sha256: 34f609b7ec5a8aa4bb292c7ee41865f69631e87eb3e3097d78762cb0b0aa9166
  - folder: cs-CZ
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-cs-CZ/{{ name }}-cs-CZ-{{ version }}.tar.gz
    sha256: dd4143ef2042b6c726d4c2e5a9228798cc827e97c4ba30058546e4146c5e8aa2
  - folder: da-DK
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-da-DK/{{ name }}-da-DK-{{ version }}.tar.gz
    sha256: 2d5f5631a7f5b6909e7d85d55f0c5b8ef46c9e4ef012ce617796898e88758719
  - folder: de-DE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-de-DE/{{ name }}-de-DE-{{ version }}.tar.gz
    sha256: 33efa0b1e118f3861f3afea7f433b26daf053d04de27b9fec7b8c327f69f7342
  - folder: el-GR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-el-GR/{{ name }}-el-GR-{{ version }}.tar.gz
    sha256: 4b1bcea5b001deafe221b3dfe71f16459eb20a716830bad57520d9b6f02a9a8e
  - folder: es-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-es-ES/{{ name }}-es-ES-{{ version }}.tar.gz
    sha256: d93f51621ba6e4aa1ae19ad7c89038b9dd7a48ddd256b5e40f24cc140d449431
  - folder: et-EE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-et-EE/{{ name }}-et-EE-{{ version }}.tar.gz
    sha256: 92bf1fedd1b5e13c85ec925c5c47403e2f96fc7597ff5f7132399529ba81b980
  - folder: fi-FI
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fi-FI/{{ name }}-fi-FI-{{ version }}.tar.gz
    sha256: 7a376ac201b60733925d0c9db30cc6cabc4595a5273825ab19c833601cf8579a
  - folder: fr-FR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fr-FR/{{ name }}-fr-FR-{{ version }}.tar.gz
    sha256: 36a115461813189ee7578835a5e467026b2c546b3fe6ba9c5394c640be8c9c44
  - folder: he-IL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-he-IL/{{ name }}-he-IL-{{ version }}.tar.gz
    sha256: 998fd2ee2a464a3b73826b919900730e95ff41f97a34b67f053cfa372d9d70fb
  - folder: hy-AM
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hy-AM/{{ name }}-hy-AM-{{ version }}.tar.gz
    sha256: 823c7097c52c0aae7e8c2a929babd88beff3ab11329fc017eaf0f23ecfafa3a3
  - folder: hu-HU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hu-HU/{{ name }}-hu-HU-{{ version }}.tar.gz
    sha256: dc5e019ea862003738a5128e2a665ccbc7f313c971a17da5837913ba2eadf964
  - folder: id-ID
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-id-ID/{{ name }}-id-ID-{{ version }}.tar.gz
    sha256: b24ea1bb018ede67a19c9e9772686593114d9a3a5341bfe0b8ab2b9a3ec7d599
  - folder: it-IT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-it-IT/{{ name }}-it-IT-{{ version }}.tar.gz
    sha256: f802790cea7d324a4f100827f095fce091e233fb2c1162fe18f847011d88a8e2
  - folder: ja-JP
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ja-JP/{{ name }}-ja-JP-{{ version }}.tar.gz
    sha256: ca4e339c8f489f06b42777b1c0ae2ac623379ed73705b7f3a809ea765c460deb
  - folder: ko-KR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ko-KR/{{ name }}-ko-KR-{{ version }}.tar.gz
    sha256: 2e9c1559894d800ec1f6e12a489eb97e9de0461db593727e4a72350c7693dff4
  - folder: lt-LT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-lt-LT/{{ name }}-lt-LT-{{ version }}.tar.gz
    sha256: 6b9d3f2c80640426a6c95a873e071ac223454bd7cb39167557b390fa98cbedcb
  - folder: nl-NL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-nl-NL/{{ name }}-nl-NL-{{ version }}.tar.gz
    sha256: 1a29eae4585a7cb101c020ea67d1df44221481f1cb5886d0ba3ef595abb23204
  - folder: no-NO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-no-NO/{{ name }}-no-NO-{{ version }}.tar.gz
    sha256: baeda9f297e105e124e725ef98da7b4d62abd31fdd27e8584d7b59037768ebdb
  - folder: pl-PL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pl-PL/{{ name }}-pl-PL-{{ version }}.tar.gz
    sha256: 69281d7f77b7716e6a9c9370f6206a92d77ab447bd6eb944a65908311c6fcaa4
  - folder: pt-BR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pt-BR/{{ name }}-pt-BR-{{ version }}.tar.gz
    sha256: 4412f39b57d08c93fe0ec9e0648330860c48e1947aa3650033b614cdef0b560a
  - folder: ro-RO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ro-RO/{{ name }}-ro-RO-{{ version }}.tar.gz
    sha256: 67df420313cdc908203f5903435b8c4d4cfff111fcf9f0a05ca2be38246c3b94
  - folder: ru-RU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ru-RU/{{ name }}-ru-RU-{{ version }}.tar.gz
    sha256: 32ac52a021a8c1cf235ba4870e51faa8a70f3f50b5b13afc15e12764d5ac373c
  - folder: tr-TR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-tr-TR/{{ name }}-tr-TR-{{ version }}.tar.gz
    sha256: dbb2eaa36b29bfa46d9f78c83c1b06335a53113153f4bb1b87b35eefc3e58a5f
  - folder: uk-UA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-uk-UA/{{ name }}-uk-UA-{{ version }}.tar.gz
    sha256: 47fdc7b4ca810e16a657b83ddf3fbb8fd20203b857da58cddc314db9df5c74c8
  - folder: vi-VN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-vi-VN/{{ name }}-vi-VN-{{ version }}.tar.gz
    sha256: 03820c3e2dc18dcf173cce2f886d264ca5a49b304087fe5698f800a3acb01dbf
  - folder: zh-CN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-CN/{{ name }}-zh-CN-{{ version }}.tar.gz
    sha256: cc8ea5a71f2c69f0aeb10804dc1d7e79fed29a601a4125c6ff36577256b77cba
  - folder: zh-TW
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-TW/{{ name }}-zh-TW-{{ version }}.tar.gz
    sha256: 36cd29d5769162508959dac755d01b549b3df7ed9ae00da87c7fd0db4d6033fb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install "./{{ locale }}" -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab/language-packs
  summary: JupyterLab {{ locale }} Language Pack
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ locale }}/LICENSE.txt
  doc_url: https://jupyterlab.readthedocs.io/
  dev_url: https://github.com/jupyterlab/language-packs

extra:
  feedstock-name: jupyterlab-language-packs
  recipe-maintainers:
    - blink1073
    - fcollonval
    - goanpeca
    - krassowski
