{% set name = "jupyterlab-language-pack" %}
{% set version = "3.2.post8" %}

package:
  name: {{ name|lower }}-{{ locale|lower }}
  version: {{ version }}

source:
  - folder: ar-SA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ar-SA/{{ name }}-ar-SA-{{ version }}.tar.gz
    sha256: f29a913355995748c3a9af119eaa2a66f19b8cd53dc9986ec1285d483ac9fd52
  - folder: ca-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ca-ES/{{ name }}-ca-ES-{{ version }}.tar.gz
    sha256: 40b61f0f6bb5be268bc772caf97ded67770956f3c2382654ac067b577df8ac06
  - folder: cs-CZ
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-cs-CZ/{{ name }}-cs-CZ-{{ version }}.tar.gz
    sha256: 6f57f0c2d5e37e1831810d2a5142354e0c4d083727e5942e299c89c3b85d9427
  - folder: da-DK
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-da-DK/{{ name }}-da-DK-{{ version }}.tar.gz
    sha256: d50bb367d0fdc0bcd3e8757c0ae7ad7ac093ba43e0d9b7bbd50c3e057c58fc4a
  - folder: de-DE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-de-DE/{{ name }}-de-DE-{{ version }}.tar.gz
    sha256: 9c941eeb49675eefee046b485b1ec06e575655e5cdb97ceb0d91165c5b9dea72
  - folder: el-GR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-el-GR/{{ name }}-el-GR-{{ version }}.tar.gz
    sha256: a64ad676150b0f7198ba7d741cdb503181876504ee4b142a1cc008c6d613afd6
  - folder: es-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-es-ES/{{ name }}-es-ES-{{ version }}.tar.gz
    sha256: 68e2b56f0a56d584f646f67ecafedefebb52798aaa533facbaaca7c01befcf65
  - folder: et-EE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-et-EE/{{ name }}-et-EE-{{ version }}.tar.gz
    sha256: 71d0b1af6ddf5825a4f866484e6bcd03b2b9c4de6ce7b8706e69181e4b210ab7
  - folder: fi-FI
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fi-FI/{{ name }}-fi-FI-{{ version }}.tar.gz
    sha256: 2c9948c227d623d8f1c24bf1d3fb7de0876fbb4b7d62af199f3a68ddd7a66205
  - folder: fr-FR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fr-FR/{{ name }}-fr-FR-{{ version }}.tar.gz
    sha256: 86bb141938c07c222b8c988fc19d151cfd794b57d00e2bb8cd88b23c1de8f7c4
  - folder: he-IL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-he-IL/{{ name }}-he-IL-{{ version }}.tar.gz
    sha256: 242456dbd33bf8a5a78cc9b77cf69c140625f88a120775b4eb89eda467527503
  - folder: hy-AM
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hy-AM/{{ name }}-hy-AM-{{ version }}.tar.gz
    sha256: a1ca4bed4a9557d4aeb712a35e33b0dd609c151ead4c1043ba68acfe84cbd0a1
  - folder: hu-HU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hu-HU/{{ name }}-hu-HU-{{ version }}.tar.gz
    sha256: d0dbd19793eeb3b393f20c877221691edb6af268b01435c9fbca079fa069ed3d
  - folder: id-ID
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-id-ID/{{ name }}-id-ID-{{ version }}.tar.gz
    sha256: 80c5d2e398ae26b4fe0fd213c98c56577274e47034ff107f665112514d7f3520
  - folder: it-IT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-it-IT/{{ name }}-it-IT-{{ version }}.tar.gz
    sha256: ace429ba96e09a9c93ab8285c129baf2d2aab8d7dbd750febebf076d392a40b1
  - folder: ja-JP
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ja-JP/{{ name }}-ja-JP-{{ version }}.tar.gz
    sha256: 09c58846d0fc21ee3224d574f8e4ab7af25eb9dfc6c3e0dc785d80b0926db05b
  - folder: ko-KR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ko-KR/{{ name }}-ko-KR-{{ version }}.tar.gz
    sha256: 8d166aa7e619e6f7f6d38cd924e348eba0a59d4038e0dbab2e752f2d39e49139
  - folder: lt-LT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-lt-LT/{{ name }}-lt-LT-{{ version }}.tar.gz
    sha256: 7c6605e03d24e9656370c32c7ed027a547d536d793636ce45cb57a8fa530d010
  - folder: nl-NL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-nl-NL/{{ name }}-nl-NL-{{ version }}.tar.gz
    sha256: 97b50ea47321ad5d13bc0ee21887fe64fd253d80f4573a88eea001fe0b01c3a7
  - folder: no-NO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-no-NO/{{ name }}-no-NO-{{ version }}.tar.gz
    sha256: bd9b1dca95cbaa6326a676c14f9e080de6c6d10b7bbfbf175021a5369e8ef277
  - folder: pl-PL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pl-PL/{{ name }}-pl-PL-{{ version }}.tar.gz
    sha256: 93cd7958750a5f17699c6f8d0a6e668456203c2c69bd08cc4b843711260118ca
  - folder: pt-BR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pt-BR/{{ name }}-pt-BR-{{ version }}.tar.gz
    sha256: 15a0277f4e73f911ac546a50af3f85f3e2d92d731afb66dd1f3973ddd6348a70
  - folder: ro-RO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ro-RO/{{ name }}-ro-RO-{{ version }}.tar.gz
    sha256: e51ed716e8ea16b22664e97f4604890dbdf0061d205e144ad530b98800c7545b
  - folder: ru-RU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ru-RU/{{ name }}-ru-RU-{{ version }}.tar.gz
    sha256: b93be3fd22d2cc86b43d1806d50499d53d7e336af9017fe786c076080461ec76
  - folder: tr-TR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-tr-TR/{{ name }}-tr-TR-{{ version }}.tar.gz
    sha256: ef86bdceb544f8c175085bbaf8ca70270e0f332f7b4477e138c24cf05a036224
  - folder: uk-UA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-uk-UA/{{ name }}-uk-UA-{{ version }}.tar.gz
    sha256: 34049088f897f1f242f0ae47ff0c55da634381a674a53c563308aecea63e7179
  - folder: vi-VN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-vi-VN/{{ name }}-vi-VN-{{ version }}.tar.gz
    sha256: 9602a017089b54fa671b08cdeae6ee8a71ac242ae119ff8426e3ad617b6b978d
  - folder: zh-CN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-CN/{{ name }}-zh-CN-{{ version }}.tar.gz
    sha256: 9e201b5d9e144ad836ec2cb5b79793a3b321ec78119dc1a399786c61b6810206
  - folder: zh-TW
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-TW/{{ name }}-zh-TW-{{ version }}.tar.gz
    sha256: 23e62d2a0cdaae3fd2654686ab6cf5b97f400817d9db703c537fe64a5e062b67

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install "./{{ locale }}" -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab/language-packs
  summary: JupyterLab {{ locale }} Language Pack
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ locale }}/LICENSE.txt
  doc_url: https://jupyterlab.readthedocs.io/
  dev_url: https://github.com/jupyterlab/language-packs

extra:
  feedstock-name: jupyterlab-language-packs
  recipe-maintainers:
    - blink1073
    - fcollonval
    - goanpeca
    - krassowski
