{% set name = "jupyterlab-language-pack" %}
{% set version = "3.2.post9" %}

package:
  name: {{ name|lower }}-{{ locale|lower }}
  version: {{ version }}

source:
  - folder: ar-SA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ar-SA/{{ name }}-ar-SA-{{ version }}.tar.gz
    sha256: 0f8e7e8a104c1e3263d2992011c18415ded22eefaf5637ea3e0e6dad3d65496b
  - folder: ca-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ca-ES/{{ name }}-ca-ES-{{ version }}.tar.gz
    sha256: 5325b46d2c72005960082853572c2679e1691d6c4d3beb5a5f2e52ff5421d092
  - folder: cs-CZ
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-cs-CZ/{{ name }}-cs-CZ-{{ version }}.tar.gz
    sha256: c354d8480c7ca3798da91a6e5a5f6d53f175c7cb23c9ced51d6dfbf66c6646d5
  - folder: da-DK
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-da-DK/{{ name }}-da-DK-{{ version }}.tar.gz
    sha256: 70896dd4deb94677173bba6471f4d40808407e325246e1f353f5cea9a81f53f3
  - folder: de-DE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-de-DE/{{ name }}-de-DE-{{ version }}.tar.gz
    sha256: 6329f0dd45b3949770761003c46179be2b81f9b642d77557dde1525b6b6e4c76
  - folder: el-GR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-el-GR/{{ name }}-el-GR-{{ version }}.tar.gz
    sha256: e591a76942b2a487e5cd591ddcf6e5113f7ff56fe96a794e7026ab419f56f689
  - folder: es-ES
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-es-ES/{{ name }}-es-ES-{{ version }}.tar.gz
    sha256: 92c14f048fd362bbedaa3301e53cade61e242c4fed05ef42bbc0fedad9637673
  - folder: et-EE
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-et-EE/{{ name }}-et-EE-{{ version }}.tar.gz
    sha256: dcd18bde9486d034d7e194b1c90300f8d873622379f24b955c8d8eff272d2870
  - folder: fi-FI
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fi-FI/{{ name }}-fi-FI-{{ version }}.tar.gz
    sha256: c9c1bf32d899a492d391cee13a086fbc399e9585bf6d9bdc6ada3b6e047c653e
  - folder: fr-FR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-fr-FR/{{ name }}-fr-FR-{{ version }}.tar.gz
    sha256: 2c8afbf85a600ac264006f6d65cdf1bb962dae6ea5c17970c50255f7b8b01e11
  - folder: he-IL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-he-IL/{{ name }}-he-IL-{{ version }}.tar.gz
    sha256: 4721304ca54b22423f66d25164c75731a40d5312b8ca2af3ef9758d39e3b993b
  - folder: hy-AM
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hy-AM/{{ name }}-hy-AM-{{ version }}.tar.gz
    sha256: 137616ff9e964dc7ad9ff6f3eadb94d54471011ffd68ed2d3be48e79ebdb6347
  - folder: hu-HU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-hu-HU/{{ name }}-hu-HU-{{ version }}.tar.gz
    sha256: 90f308a749f9dd0c64c2ca0e5a151df953b23fa6cfd85d4972ba872e0582e07c
  - folder: id-ID
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-id-ID/{{ name }}-id-ID-{{ version }}.tar.gz
    sha256: 22703cb4960ee1f8d63e46e02ddfcb70c7d78d08743f24138047a3322be57cea
  - folder: it-IT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-it-IT/{{ name }}-it-IT-{{ version }}.tar.gz
    sha256: 95155d1490855f934e2642b5cf5c9ebeecb0b64494394b7939a4cea8931296f1
  - folder: ja-JP
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ja-JP/{{ name }}-ja-JP-{{ version }}.tar.gz
    sha256: 7ff30da6b172b604178187ba256edf44b558d1ba8f4bf563fb040d1574aee459
  - folder: ko-KR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ko-KR/{{ name }}-ko-KR-{{ version }}.tar.gz
    sha256: 2d01892d9807990b1f8d64cd59136d6e4c6255a30eab0e8bfb6f2ba46cc1a076
  - folder: lt-LT
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-lt-LT/{{ name }}-lt-LT-{{ version }}.tar.gz
    sha256: 5ac2df66d9bec02817e8bad7f62768d28d1407217831c990bd8030f098f342fc
  - folder: nl-NL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-nl-NL/{{ name }}-nl-NL-{{ version }}.tar.gz
    sha256: acd8d229232b2ed89973efb64f4f068d75c6a7d74f76f65f16e57e9115e18532
  - folder: no-NO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-no-NO/{{ name }}-no-NO-{{ version }}.tar.gz
    sha256: b072a9dd89500a3f830ca87716882c0a6f7bed84440ef0a7d089f727bccac8a3
  - folder: pl-PL
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pl-PL/{{ name }}-pl-PL-{{ version }}.tar.gz
    sha256: aa423d4661f39e18c2313e9bb864199a21a32d38b393e02a91f4b1ef5955365a
  - folder: pt-BR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-pt-BR/{{ name }}-pt-BR-{{ version }}.tar.gz
    sha256: 323fc8bb1926b616aaf4e4ae66d817b3ddb9058a2656a97393e886b73f22cf7c
  - folder: ro-RO
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ro-RO/{{ name }}-ro-RO-{{ version }}.tar.gz
    sha256: f09db2bb316f699dbfc32a7895138a4d85b464530e5f484da92041278c790c4e
  - folder: ru-RU
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-ru-RU/{{ name }}-ru-RU-{{ version }}.tar.gz
    sha256: 00f7426a3b191318fca9546b204b404e21393f03fc3535d791a05abc28c8659e
  - folder: tr-TR
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-tr-TR/{{ name }}-tr-TR-{{ version }}.tar.gz
    sha256: 8b1917790c76e90779a30f9f3fa130607622635a303cb8a2a9c830144d0e8120
  - folder: uk-UA
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-uk-UA/{{ name }}-uk-UA-{{ version }}.tar.gz
    sha256: 4dfe4a74d0df9f286d73be39ee1ad3205ca32f9060308ff7f95a50189593bac3
  - folder: vi-VN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-vi-VN/{{ name }}-vi-VN-{{ version }}.tar.gz
    sha256: 4e3179e48321a14dec6c7e0f4c8d488f4eb2e87d394169ec08de26f54f510af7
  - folder: zh-CN
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-CN/{{ name }}-zh-CN-{{ version }}.tar.gz
    sha256: 2ef0e7c2a3beed85d70a83f5c998dc457582fa6bbe7e45cf38ee2fb0a636dca1
  - folder: zh-TW
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-zh-TW/{{ name }}-zh-TW-{{ version }}.tar.gz
    sha256: 052ed959555af272babc026f2af5431efc57f7e2879f18029bf4bff7392fd013

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install "./{{ locale }}" -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab/language-packs
  summary: JupyterLab {{ locale }} Language Pack
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ locale }}/LICENSE.txt
  doc_url: https://jupyterlab.readthedocs.io/
  dev_url: https://github.com/jupyterlab/language-packs

extra:
  feedstock-name: jupyterlab-language-packs
  recipe-maintainers:
    - blink1073
    - fcollonval
    - goanpeca
    - krassowski
